dependencies:
- alias: tekton
  name: tekton
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.32
- alias: prow
  name: prow
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.500
- name: jenkins-x-platform
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.3877
- name: external-dns
  repository: https://charts.bitnami.com/bitnami
  version: 1.5.2
- condition: chartmuseum.enabled
  name: chartmuseum
  repository: http://chartmuseum.jenkins-x.io
  version: 1.1.4
- name: datadog
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 1.26.0
- name: jx-app-athens
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.16
- name: jx-app-sso
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.7
- name: 3a1983a1-adfa-4007-bfc1-d967dee1cf0a
  repository: http://chartmuseum.jenkins-x.io
  version: 1.0.0
