dependencies:
- alias: tekton
  name: tekton
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.32
- alias: prow
  name: prow
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.484
- name: jenkins-x-platform
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.3833
- name: external-dns
  repository: https://charts.bitnami.com/bitnami
  version: 1.5.2
- condition: chartmuseum.enabled
  name: chartmuseum
  repository: http://chartmuseum.jenkins-x.io
  version: 1.1.4
- name: datadog
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 1.26.0
- name: jx-app-athens
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.16
- name: cb-app-slack
  repository: https://chartmuseum.jx.charts-demo.cloudbees.com
  version: 0.0.37
