dependencies:
- alias: tekton
  name: tekton
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.38
- alias: prow
  name: prow
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.620
- name: jenkins-x-platform
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.3877
- name: external-dns
  repository: https://charts.bitnami.com/bitnami
  version: 1.5.2
- condition: chartmuseum.enabled
  name: chartmuseum
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 1.1.4
- name: datadog
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 1.26.0
- name: jx-app-athens
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.17
- name: jx-app-sso
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.10
- name: jx-app-ui
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.792
- name: jx-app-replicator
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 1.0.14
- name: jxui-backup
  repository: http://chart.infra.jrawlings.co.uk
  version: 0.0.4
